/**
 * @fileoverview Centralizes reusable EMS presentation and domain defaults. It defines status-to-color mappings for employees, attendance, and payroll, plus the complete blank employee shape used by create and edit forms.
 *
 * @description
 * This module is part of the Employee Management System client. The summary above describes
 * its ownership boundary so maintainers can quickly identify why it exists and how it participates
 * in the surrounding UI, state, or data flow.
 *
 * @module src/constants/EMSconstants
 */
export const STATUS_COLORS = {
	Active: "bg-emerald-100 text-emerald-700",
	Resigned: "bg-red-100 text-red-700",
	OnLeave: "bg-amber-100 text-amber-700",
	Probation: "bg-blue-100 text-blue-700",
};

export const ATTENDANCE_STATUS_COLORS = {
	Present: "bg-emerald-100 text-emerald-700",
	Absent: "bg-red-100 text-red-700",
	Leave: "bg-amber-100 text-amber-700",
};

export const ATTENDANCE_PERCENTAGE_COLORS = {
	EXCELLENT: "bg-green-100 text-green-700",
	AVERAGE: "bg-yellow-100 text-yellow-700",
	POOR: "bg-red-100 text-red-700",
};

export const PAYROLL_STATUS_COLORS = {
	Paid: "bg-emerald-100 text-emerald-700",
	Processing: "bg-sky-100 text-sky-700",
	Pending: "bg-amber-100 text-amber-700",
};

// Matches the bank names generated by the backend seed.
export const BANK_NAMES = ["HDFC Bank", "ICICI Bank", "Axis Bank", "SBI", "Kotak Mahindra Bank"];

export const EMPLOYEE_DEFAULT_VALUES = {
	id: "",
	employeeId: "",
	employeeCode: "",
	fullName: "",
	email: "",

	personalInfo: {
		firstName: "",
		lastName: "",
		gender: "",
		dateOfBirth: "",
		maritalStatus: "",
		bloodGroup: "",
		nationality: "",
		phone: "",
		alternatePhone: "",
		profileImage: "",
	},

	address: {
		currentAddress: {
			street: "",
			city: "",
			state: "",
			country: "",
			pincode: "",
		},

		permanentAddress: {
			street: "",
			city: "",
			state: "",
			country: "",
			pincode: "",
		},
	},

	employment: {
		designationId: "",
		designationGlobalId: "",
		designation: "",
		departmentId: "",
		departmentGlobalId: "",
		departmentName: "",
		orgRole: "",
		employeeType: "",
		joiningDate: "",
		workMode: "",
		workLocation: "",
		status: "Active",
		probationEndDate: "",
		probationStatus: "",
		lead: {
			id: "",
			employeeId: "",
			name: "",
		},
		manager: {
			id: "",
			employeeId: "",
			name: "",
		},
		hr: {
			id: "",
			employeeId: "",
			name: "",
		},
	},

	bankDetails: {
		bankName: "",
		accountNumber: "",
		ifscCode: "",
		branch: "",
	},

	emergencyContact: {
		name: "",
		relationship: "",
		phone: "",
	},
};
